volumes:
  app-dynamodb-data:
  app-postgres-data:
  app-python-packages:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - app-python-packages:/app/.venv
    ports:
      - "8080:8080"
    networks:
      - app-network

  dynamodb:
    image: amazon/dynamodb-local:latest
    user: root
    ports:
      - "8000:8000"
    # -sharedDb: 必須。これがないと接続ごとに別ファイル扱いになることがある
    # -dbPath: データを /home/dynamodblocal/data に保存するよう指示
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      # 2. 作成したボリュームをデータ保存先にマウント
      - app-dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - app-network

  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - app-postgres-data:/var/lib/postgresql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
